version: "3"

services:
  connect:
    container_name: db
    image: postgres:11.8
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
  web:
    container_name: web_start
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
          DB_HOST: connect
          DB_PORT: ${DB_PORT}
          DB_USER: ${DB_USERNAME}
          DB_PASSWORD: ${DB_PASSWORD}
          DB_NAME: ${DB_NAME}
    ports:
      - "3000:3000"
    depends_on:
      - connect

